/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Topic = IDL.Variant({
  'russianEmpire' : IDL.Null,
  'februaryRevolution' : IDL.Null,
  'afterFebruary' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const MCQ = IDL.Record({
  'topic' : Topic,
  'question' : IDL.Text,
  'difficulty' : Difficulty,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Answer = IDL.Record({
  'questionIndex' : IDL.Nat,
  'selectedOption' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getQuestions' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
  'submitAnswers' : IDL.Func([IDL.Vec(Answer)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Topic = IDL.Variant({
    'russianEmpire' : IDL.Null,
    'februaryRevolution' : IDL.Null,
    'afterFebruary' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MCQ = IDL.Record({
    'topic' : Topic,
    'question' : IDL.Text,
    'difficulty' : Difficulty,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Answer = IDL.Record({
    'questionIndex' : IDL.Nat,
    'selectedOption' : IDL.Nat,
  });
  
  return IDL.Service({
    'getQuestions' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
    'submitAnswers' : IDL.Func([IDL.Vec(Answer)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };